import type { ArchitectureModel } from '../model/architecture-model.js';

export const helloArchitecture: ArchitectureModel = {
  name: 'AI Agents Architecture',
  nodes: [
    { id: 'chatgpt', label: 'ChatGPT', group: 'Entry Points' },
    { id: 'cursor', label: 'Cursor', group: 'Entry Points' },
    { id: 'claude-code', label: 'Claude Code', group: 'Entry Points' },
    { id: 'vs-code', label: 'VS Code', group: 'Entry Points' },
    { id: 'agent-runtime', label: 'Agent Runtime' },
    { id: 'context-assembly', label: 'Context Assembly' },
    { id: 'prompt-construction', label: 'Prompt Construction' },
    { id: 'openrouter', label: 'OpenRouter', group: 'Model Provider' },
    { id: 'anthropic', label: 'Anthropic', group: 'Model Provider' },
    { id: 'openai', label: 'OpenAI', group: 'Model Provider' },
    { id: 'google', label: 'Google', group: 'Model Provider' },
    { id: 'llm', label: 'LLM' },
    { id: 'filesystem', label: 'Filesystem', group: 'Tools' },
    { id: 'git', label: 'Git', group: 'Tools' },
    { id: 'terminal', label: 'Terminal', group: 'Tools' },
    { id: 'mcp', label: 'MCP', group: 'Tools' },
    { id: 'web-search', label: 'Web Search', group: 'Tools' },
  ],
  edges: [
    { sourceId: 'chatgpt', targetId: 'agent-runtime' },
    { sourceId: 'cursor', targetId: 'agent-runtime' },
    { sourceId: 'claude-code', targetId: 'agent-runtime' },
    { sourceId: 'vs-code', targetId: 'agent-runtime' },
    { sourceId: 'agent-runtime', targetId: 'context-assembly' },
    { sourceId: 'context-assembly', targetId: 'prompt-construction' },
    { sourceId: 'prompt-construction', targetId: 'openrouter' },
    { sourceId: 'prompt-construction', targetId: 'anthropic' },
    { sourceId: 'prompt-construction', targetId: 'openai' },
    { sourceId: 'prompt-construction', targetId: 'google' },
    { sourceId: 'openrouter', targetId: 'llm' },
    { sourceId: 'anthropic', targetId: 'llm' },
    { sourceId: 'openai', targetId: 'llm' },
    { sourceId: 'google', targetId: 'llm' },
    { sourceId: 'llm', targetId: 'filesystem' },
    { sourceId: 'llm', targetId: 'git' },
    { sourceId: 'llm', targetId: 'terminal' },
    { sourceId: 'llm', targetId: 'mcp' },
    { sourceId: 'llm', targetId: 'web-search' },
  ],
};
